import { test,expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
test('human connected proof survives reload without console errors or overflow',async({page},testInfo)=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  const session=JSON.parse(readFileSync('.local/demo-session.json','utf8'));
  await page.goto('/');
  await page.getByLabel('Token de sesión local').fill(session.token);
  await page.getByRole('button',{name:'Entrar al workspace'}).click();
  await expect(page.getByRole('heading',{name:'Una decisión conecta con la siguiente.'})).toBeVisible();
  await page.getByLabel('Nueva Brand',{exact:true}).fill(`Browser DEMO ${testInfo.project.name} ${Date.now()}`);
  await page.getByRole('button',{name:'Crear Brand',exact:true}).click();
  await expect(page.locator('#decision')).toContainText('POR DECIDIR');
  async function approve(option:string,rationale:string,button='Preparar decisión') {
    await page.getByRole('button',{name:button,exact:true}).click();
    await page.getByLabel('Decisión propuesta').fill(option);
    await page.getByLabel('¿Por qué eliges esta opción?').fill(rationale);
    await page.getByRole('button',{name:'Aprobar decisión',exact:true}).click();
    await expect(page.locator('#decision .current')).toHaveText(option);
  }
  await approve('Agencies','Servicio recurrente para múltiples marcas');
  await page.getByRole('button',{name:'02 Positioning'}).click();
  await approve('Strategic OS for Agencies','Continuidad del criterio estratégico');
  await page.getByRole('button',{name:'01 Customer'}).click();
  await approve('Internal Marketing Teams','Cambio humano de cliente prioritario','Preparar nueva versión');
  await page.getByText('Historial · 2 versiones',{exact:true}).click();
  await expect(page.locator('.history-item').filter({hasText:'SUPERSEDED'})).toContainText('Agencies');
  await page.getByRole('button',{name:'02 Positioning'}).click();
  await expect(page.locator('#decision')).toContainText('NEEDS REVIEW');
  await expect(page.locator('#decision .current')).toHaveText('Strategic OS for Agencies');
  await page.getByRole('button',{name:'Ver impacto',exact:true}).click();
  await expect(page.locator('#decision')).toContainText('versión 1 → 2');
  await page.screenshot({path:`test-results/m1-impact-${testInfo.project.name}.png`,fullPage:true});
  await page.reload();
  await expect(page.locator('#decision')).toContainText('NEEDS REVIEW');
  await approve('Strategic OS for Internal Marketing Teams','Revisión humana tras el cambio de cliente','Iniciar revisión humana');
  await page.reload();
  await expect(page.locator('#decision')).toContainText('APROBADA · v2');
  await expect(page.locator('#decision')).not.toContainText('NEEDS REVIEW');
  await page.getByText('Historial · 2 versiones',{exact:true}).click();
  await expect(page.locator('.history-item')).toHaveCount(2);
  await expect(page.locator('.history-item').filter({hasText:'SUPERSEDED'})).toContainText('Strategic OS for Agencies');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:`test-results/m1-completed-${testInfo.project.name}.png`,fullPage:true});
  expect(errors).toEqual([]);
  await page.getByRole('button',{name:'Salir',exact:true}).click();
  await expect(page.getByLabel('Token de sesión local')).toBeVisible();
});
test('two human tabs cannot silently overwrite a newer version',async({page,context})=>{
  const session=JSON.parse(readFileSync('.local/demo-session.json','utf8'));
  await page.goto('/');await page.getByLabel('Token de sesión local').fill(session.token);await page.getByRole('button',{name:'Entrar al workspace'}).click();
  await page.getByLabel('Nueva Brand',{exact:true}).fill(`Concurrency DEMO ${Date.now()}`);await page.getByRole('button',{name:'Crear Brand',exact:true}).click();await expect(page.locator('#decision')).toContainText('POR DECIDIR');
  await page.getByRole('button',{name:'Preparar decisión',exact:true}).click();await page.getByLabel('Decisión propuesta').fill('Original');await page.getByLabel('¿Por qué eliges esta opción?').fill('Original rationale');await page.getByRole('button',{name:'Aprobar decisión',exact:true}).click();await expect(page.locator('#decision .current')).toHaveText('Original');
  const second=await context.newPage();await second.goto(page.url());await expect(second.locator('#decision .current')).toHaveText('Original');
  await page.getByRole('button',{name:'Preparar nueva versión',exact:true}).click();await second.getByRole('button',{name:'Preparar nueva versión',exact:true}).click();
  await page.getByLabel('Decisión propuesta').fill('Newer');await page.getByLabel('¿Por qué eliges esta opción?').fill('Newer rationale');await page.getByRole('button',{name:'Aprobar decisión',exact:true}).click();await expect(page.locator('#decision .current')).toHaveText('Newer');
  await second.getByLabel('Decisión propuesta').fill('Stale');await second.getByLabel('¿Por qué eliges esta opción?').fill('Stale rationale');await second.getByRole('button',{name:'Aprobar decisión',exact:true}).click();
  await expect(second.getByRole('status')).toContainText('El estado cambió');await expect(second.getByLabel('Decisión propuesta')).toHaveValue('Stale');
  await second.getByRole('button',{name:'Recargar contexto',exact:true}).click();await expect(second.locator('#decision .current')).toHaveText('Newer');
  await second.getByText('Historial · 2 versiones',{exact:true}).focus();await second.keyboard.press('Enter');await expect(second.locator('.history-item')).toHaveCount(2);await expect(second.locator('.history-item').first()).toBeVisible();
  await second.close();
});
