import { createServer as httpsServer } from 'node:https';
import { request } from 'node:http';
import type { AddressInfo } from 'node:net';
import { readFileSync,writeFileSync,mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import * as oidc from 'openid-client';
import { databaseUrl } from '../scripts/local-db.js';
import { connect } from '../src/persistence/database.js';
import { migrateDatabase } from '../scripts/migrate.js';
import { PilotAccess } from '../src/application/pilot-access.js';
import { Engine } from '../src/application/engine.js';
import { ModelGateway } from '../src/domain/analysis.js';
import { UnavailableProvider } from '../src/transport/anthropic-provider.js';
import { PilotAuth } from '../src/transport/pilot-auth.js';
import { createApp } from '../src/transport/http.js';
import { runtimeAssets } from '../src/transport/server.js';
import { readiness } from '../src/persistence/readiness.js';
// Test-only operator fixtures; never imported by pilot:start. No HTTP provisioning bypass.
if(process.env.DATABASE_URL)throw new Error('Browser fixtures require the local development DB.');
const folder='.local/pilot-browser';mkdirSync(folder,{recursive:true});
execFileSync(process.env.OPENSSL_BIN??(process.platform==='win32'?'C:/Program Files/Git/usr/bin/openssl.exe':'openssl'),['req','-x509','-newkey','rsa:2048','-nodes','-keyout',folder+'/key.pem','-out',folder+'/cert.pem','-days','1','-subj','/CN=127.0.0.1','-addext','subjectAltName=IP:127.0.0.1'],{stdio:'ignore'});
const admin=connect(databaseUrl()),name=`pilot_browser_${randomUUID().replaceAll('-','')}`;await admin.pool.query(`CREATE DATABASE "${name}"`);await admin.pool.end();
const db=connect(databaseUrl().replace(/\/postgres$/,`/${name}`));await migrateDatabase(db.db);
const issuer='https://browser-idp.example',access=new PilotAccess(db.db,issuer);await access.provision('tester-a','A');await access.provision('tester-b','B');
writeFileSync(folder+'/sessions.json',JSON.stringify({a:await access.issueSession('tester-a'),b:await access.issueSession('tester-b')}),{mode:0o600});
const origin='https://127.0.0.1:3002',auth=new PilotAuth(db.db,new oidc.Configuration({issuer,authorization_endpoint:issuer+'/authorize',token_endpoint:issuer+'/token',jwks_uri:issuer+'/keys'},'fixture-client','fixture-secret'),origin);
const app=createApp(new Engine(db.db,undefined,new ModelGateway(new UnavailableProvider(),'pilot-strategic-v1')),path=>{const entry=runtimeAssets[path as keyof typeof runtimeAssets];return entry?{content:readFileSync(entry[0]),type:entry[1]}:undefined;},()=>readiness(db.pool),auth);
await new Promise<void>(r=>app.listen(0,'127.0.0.1',r));
const server=httpsServer({key:readFileSync(folder+'/key.pem'),cert:readFileSync(folder+'/cert.pem')},(req,res)=>{const upstream=request({host:'127.0.0.1',port:(app.address() as AddressInfo).port,path:req.url,method:req.method,headers:req.headers},response=>{res.writeHead(response.statusCode??503,response.headers);response.pipe(res);});upstream.on('error',()=>{res.writeHead(503);res.end();});req.pipe(upstream);});
server.listen(3002,'127.0.0.1');let closing=false;const stop=async()=>{if(closing)return;closing=true;await new Promise<void>(r=>server.close(()=>r()));await new Promise<void>(r=>app.close(()=>r()));await db.pool.end();};process.once('SIGINT',stop);process.once('SIGTERM',stop);
