// Engineering Skill Pack mirror. `.agents/skills/` is the canonical source (read by Codex and other agents);
// `.claude/skills/` is a generated byte-for-byte copy for Claude Code and is never edited by hand. No symlinks:
// Git for Windows checks them out as plain text files by default. Engineering tooling only, never imported by
// the runtime.
import { copyFileSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, realpathSync, renameSync, rmSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const SKILLS_SOURCE = '.agents/skills';
export const SKILLS_COPY = '.claude/skills';
export const USAGE = 'Usage: pnpm skills:sync (regenerate .claude/skills) | pnpm skills:check (report drift, never writes)';

/** File operations used by sync; injectable so tests can force failures at each step. */
export interface SyncOps { copyFile: (from: string, to: string) => void; rename: (from: string, to: string) => void }
const defaultOps: SyncOps = { copyFile: copyFileSync, rename: renameSync };

const isLink = (path: string) => { try { return lstatSync(path).isSymbolicLink(); } catch { return false; } };
const inside = (child: string, parent: string) => {
  const rel = relative(parent, child);
  return rel === '' || (!rel.startsWith('..') && !rel.startsWith(sep) && !/^[a-zA-Z]:/.test(rel));
};

/**
 * Problems with one skill root (`rel` inside `root`). Only the part of the path inside the repository is
 * inspected: the root folder and every parent up to the repository (e.g. `.claude`) must be real directories,
 * never symlinks or junctions. Aliases above the repository (macOS /var → /private/var, Windows 8.3 names,
 * mapped drives) are legitimate and ignored.
 */
export function rootProblems(root: string, rel: string, mustExist: boolean): string[] {
  const parts = rel.split('/');
  for (let i = 1; i <= parts.length; i++) {
    const segment = join(root, ...parts.slice(0, i));
    if (isLink(segment)) return [`${parts.slice(0, i).join('/')} is a symlink or junction; it must be a real directory`];
    if (!existsSync(segment)) return mustExist ? [`${rel} does not exist`] : [];
    if (!lstatSync(segment).isDirectory()) return [`${parts.slice(0, i).join('/')} is not a directory`];
  }
  return [];
}

/** Both roots valid and physically distinct, neither nested in the other. */
export function layoutProblems(root = ROOT, copyMustExist = true): string[] {
  const source = join(root, SKILLS_SOURCE), copy = join(root, SKILLS_COPY);
  const problems = [...rootProblems(root, SKILLS_SOURCE, true), ...rootProblems(root, SKILLS_COPY, copyMustExist)];
  if (!problems.length && existsSync(copy)) {
    const a = realpathSync.native(source), b = realpathSync.native(copy);
    if (inside(a, b) || inside(b, a)) problems.push(`${SKILLS_SOURCE} and ${SKILLS_COPY} resolve to overlapping locations`);
  }
  return problems;
}

/** Relative file paths under `dir` (forward slashes, sorted). Symlinks and junctions are rejected, not followed. */
export function listFiles(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const out: string[] = [];
  const walk = (current: string) => {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const full = join(current, entry.name);
      if (isLink(full)) throw new Error(`Symlink or junction not allowed in skill pack: ${full}`);
      if (entry.isDirectory()) walk(full);
      else out.push(relative(dir, full).split(sep).join('/'));
    }
  };
  walk(dir);
  return out.sort();
}

interface Drift { missing: string[]; changed: string[]; copyOnly: string[] }
function drift(source: string, copy: string): Drift {
  const a = listFiles(source), b = listFiles(copy), inCopy = new Set(b), inSource = new Set(a);
  return {
    missing: a.filter(f => !inCopy.has(f)),
    changed: a.filter(f => inCopy.has(f) && !readFileSync(join(source, f)).equals(readFileSync(join(copy, f)))),
    copyOnly: b.filter(f => !inSource.has(f)),
  };
}

/** Every difference between the canonical source and the Claude Code copy. Read-only; empty means identical. */
export function compareSkillCopies(root = ROOT): string[] {
  try {
    const layout = layoutProblems(root);
    if (layout.length) return layout;
    const source = join(root, SKILLS_SOURCE);
    if (!listFiles(source).length) return [`${SKILLS_SOURCE} has no files`];
    const d = drift(source, join(root, SKILLS_COPY));
    return [...d.missing.map(f => `missing in ${SKILLS_COPY}: ${f}`), ...d.changed.map(f => `bytes differ: ${f}`),
      ...d.copyOnly.map(f => `only in ${SKILLS_COPY} (move it to ${SKILLS_SOURCE} or delete it; sync refuses): ${f}`)];
  } catch (error) { return [(error as Error).message]; }
}

/**
 * Regenerates `.claude/skills/` from `.agents/skills/` without ever writing into the source. Refuses linked or
 * overlapping roots and any file that exists only in the copy (it would be lost). The new copy is built and
 * verified in a sibling staging folder; the old copy is moved to a backup, the staging folder takes its place,
 * and the backup is restored if that swap fails. Returns the copied count and the drifted files it replaced.
 */
export function syncSkillCopies(root = ROOT, ops: SyncOps = defaultOps): { copied: number; replaced: string[] } {
  const layout = layoutProblems(root, false);
  if (layout.length) throw new Error(`Refusing to sync:\n- ${layout.join('\n- ')}`);
  const source = join(root, SKILLS_SOURCE), copy = join(root, SKILLS_COPY), files = listFiles(source);
  if (!files.length) throw new Error(`${SKILLS_SOURCE} has no files`);
  const current = existsSync(copy) ? drift(source, copy) : { missing: [], changed: [], copyOnly: [] };
  if (current.copyOnly.length) throw new Error(`Refusing to sync: these files exist only in ${SKILLS_COPY} and would be lost. Move real skills into ${SKILLS_SOURCE} or delete them explicitly, then sync again:\n- ${current.copyOnly.join('\n- ')}`);
  const stamp = `${process.pid}-${Date.now()}`, staging = `${copy}.staging-${stamp}`, backup = `${copy}.previous-${stamp}`;
  mkdirSync(dirname(copy), { recursive: true });
  try {
    for (const file of files) {
      mkdirSync(dirname(join(staging, file)), { recursive: true });
      ops.copyFile(join(source, file), join(staging, file));
    }
    const staged = drift(source, staging);
    if (staged.missing.length || staged.changed.length || staged.copyOnly.length) throw new Error(`Staging copy failed verification; ${SKILLS_COPY} was not touched`);
    const hadCopy = existsSync(copy);
    if (hadCopy) ops.rename(copy, backup);
    try { ops.rename(staging, copy); }
    catch (error) {
      if (hadCopy) ops.rename(backup, copy);
      throw new Error(`Swap failed; previous ${SKILLS_COPY} restored: ${(error as Error).message}`);
    }
  } finally {
    rmSync(staging, { recursive: true, force: true });
  }
  rmSync(backup, { recursive: true, force: true });
  return { copied: files.length, replaced: current.changed };
}

/** CLI entry: no argument syncs, `--check` only reports. Anything else is refused before touching a file. */
export function runCli(args: string[], root = ROOT, log: (line: string) => void = console.log, error: (line: string) => void = console.error): number {
  if (args.length > 1 || (args.length === 1 && args[0] !== '--check')) {
    error(`Unknown argument(s): ${args.join(' ')}\n${USAGE}`);
    return 2;
  }
  if (args[0] === '--check') {
    const problems = compareSkillCopies(root);
    if (problems.length) {
      error(`${SKILLS_COPY} diverges from ${SKILLS_SOURCE}:\n- ${problems.join('\n- ')}\nReview the drift: edit only ${SKILLS_SOURCE}, then pnpm skills:sync (it refuses linked roots and copy-only files).`);
      return 1;
    }
    log(`${SKILLS_COPY} is byte-identical to ${SKILLS_SOURCE}.`);
    return 0;
  }
  try {
    const { copied, replaced } = syncSkillCopies(root);
    if (replaced.length) log(`Replaced drifted generated files in ${SKILLS_COPY} (the copy is never edited by hand):\n- ${replaced.join('\n- ')}`);
    log(`Copied ${copied} file(s) from ${SKILLS_SOURCE} to ${SKILLS_COPY}.`);
    return 0;
  } catch (e) {
    error((e as Error).message);
    return 1;
  }
}
