// Engineering Skill Pack mirror. `.agents/skills/` is the canonical source (read by Codex and other agents);
// `.claude/skills/` is a generated byte-for-byte copy for Claude Code. No symlinks: Git for Windows checks them
// out as plain text files by default. Engineering tooling only, never imported by the runtime.
import { existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const SKILLS_SOURCE = '.agents/skills';
export const SKILLS_COPY = '.claude/skills';

/** Relative file paths under `dir` (forward slashes, sorted). Symlinks are rejected, not followed. */
export function listFiles(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const out: string[] = [];
  const walk = (current: string) => {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const full = join(current, entry.name);
      if (lstatSync(full).isSymbolicLink()) throw new Error(`Symlink not allowed in skill pack: ${relative(ROOT, full)}`);
      if (entry.isDirectory()) walk(full);
      else out.push(relative(dir, full).split(sep).join('/'));
    }
  };
  walk(dir);
  return out.sort();
}

/** Every difference between the canonical source and the Claude Code copy. Empty means byte-identical. */
export function compareSkillCopies(root = ROOT): string[] {
  const source = join(root, SKILLS_SOURCE), copy = join(root, SKILLS_COPY);
  const a = listFiles(source), b = listFiles(copy), problems: string[] = [];
  if (!a.length) problems.push(`${SKILLS_SOURCE} has no files`);
  for (const file of a) {
    if (!b.includes(file)) problems.push(`missing in ${SKILLS_COPY}: ${file}`);
    else if (!readFileSync(join(source, file)).equals(readFileSync(join(copy, file)))) problems.push(`bytes differ: ${file}`);
  }
  for (const file of b) if (!a.includes(file)) problems.push(`not in ${SKILLS_SOURCE} (edit the source, then sync): ${file}`);
  return problems;
}

/** Regenerates `.claude/skills/` from `.agents/skills/`. The copy is fully generated, so it is replaced. */
export function syncSkillCopies(root = ROOT): number {
  const source = join(root, SKILLS_SOURCE), copy = join(root, SKILLS_COPY), files = listFiles(source);
  if (!files.length) throw new Error(`${SKILLS_SOURCE} has no files`);
  rmSync(copy, { recursive: true, force: true });
  for (const file of files) {
    const target = join(copy, file);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, readFileSync(join(source, file)));
  }
  return files.length;
}
