import { createHash,randomBytes,randomUUID } from 'node:crypto';
import { and,asc,count,eq,gt,inArray,or } from 'drizzle-orm';
import type { Database } from '../persistence/database.js';
import * as t from '../persistence/schema.js';
import { AppError } from '../domain/contracts.js';
import { Engine,hash } from './engine.js';

/**
 * Participant access lifecycle. All three states exist in the model from the start so a future
 * controlled pilot or admin enforcement is a configuration change, not a schema redesign:
 *   PENDING   - account exists, access withheld until something approves it
 *   APPROVED  - full access to the participant's private workspace
 *   SUSPENDED - access withdrawn by an operator, account preserved
 * Which state a NEW participant starts in is policy, never hardcoded business logic: see
 * pilotDefaultAccessStatus() in src/transport/pilot-auth.ts.
 *
 * The status lives on user_accounts, the self-service participant profile, and deliberately NOT on
 * pilot_identities: that table is shared with the frozen Pilot build exercised by the release
 * rehearsal, and widening it breaks that compatibility test. An identity provisioned by an operator
 * has no profile row and is therefore treated as APPROVED, which preserves existing behaviour exactly;
 * disable() remains the control for those.
 */
/**
 * Strategic market a brand competes in and wants to grow into. Canonical rule: a brand's operating
 * location is NOT its strategic market, so this is asked rather than inferred.
 */
/** Professional profile of the Estratega de Marca, captured once at intake. */
export const PARTICIPANT_PROFILES=Object.freeze(['EMPRENDEDOR','FUNDADOR','CONSULTOR','AGENCIA','MARKETING','ESTRATEGIA','DIRECCION','DOCENCIA','OTRO'] as const);
export type ParticipantProfile=typeof PARTICIPANT_PROFILES[number];

export const GEOGRAPHIC_INFLUENCE=Object.freeze(['LOCAL','REGIONAL','STATE','NATIONAL','LATAM','GLOBAL'] as const);
export type GeographicInfluence=typeof GEOGRAPHIC_INFLUENCE[number];

/** The canonical demonstration brand seeded into every self-service workspace as its own sandbox copy. */
export const DEMO_BRAND=Object.freeze({
  name:'CoffeePolis',
  geographicInfluence:'LOCAL' as GeographicInfluence,
  primaryMarket:'Xalapa, Veracruz',
  context:'CoffeePolis es una marca de café urbano en Xalapa, Veracruz, dirigida principalmente a millennials con poder adquisitivo medio. Su experiencia diferenciada combina café de autor con barista, arte curado, Coffee Raves, catas de café, mocktails y experiencias de comunidad alrededor del café. Intención estratégica: ofrecer una experiencia de café y cultura diferenciada en la ciudad de Xalapa, Veracruz.'
});

/**
 * The demonstration strategy seeded into CoffeePolis so a new Estratega de Marca can see what a worked
 * Brandopolis brand looks like rather than an empty one. Deterministic fixture content, authored here:
 * nothing is generated by an AI provider, and nothing claims to be external research.
 */
export const DEMO_STRATEGY=Object.freeze({
  // Decision Spine order (ADR-0021): seeding upstream first means no connected decision predates its upstream.
  decisions:Object.freeze([
    Object.freeze({module:'Strategic Objective',
      option:'Convertir a CoffeePolis en el punto de encuentro estable de café de autor y cultura en Xalapa; el avance se reconoce en visitas recurrentes y en la asistencia a eventos de comunidad',
      rationale:'La escena cultural de la ciudad está dispersa. El objetivo no es vender más café a cualquier costo, sino construir un lugar al que se vuelve; por eso el progreso se observa en recurrencia y comunidad, no en una sola cifra de ventas.'}),
    Object.freeze({module:'Market Arena',
      option:'Experiencias de café y cultura en Xalapa, frente a cafeterías de especialidad, espacios culturales y quedarse en casa; por ahora quedan fuera la venta de grano, las franquicias y otras ciudades',
      rationale:'La marca opera en Xalapa, pero su ubicación no define por sí sola la arena: compite por el tiempo libre de quien busca una experiencia, no sólo por la taza. Delimitar lo que queda fuera evita dispersar recursos antes de validar la comunidad.'}),
    Object.freeze({module:'Primary Customer',
      option:'Millennials de Xalapa con poder adquisitivo medio que buscan una experiencia cultural, no sólo un café',
      rationale:'Es el grupo que ya sostiene la escena cultural de la ciudad y que elige dónde consumir por la experiencia y la comunidad, no por el precio. Concentrarse en él permite diseñar la carta, el espacio y los eventos alrededor de una sola expectativa en lugar de intentar servir a todos.'}),
    Object.freeze({module:'Value Mechanism',
      option:'Ingreso recurrente por experiencia: consumo diario de café de autor sostenido por catas, Coffee Raves y eventos de comunidad',
      rationale:'El café de barista da la frecuencia y las experiencias dan el margen y la razón para volver. Una cosa sin la otra deja el negocio dependiendo del tráfico de paso.'}),
    Object.freeze({module:'Positioning',
      option:'La casa de café y cultura de Xalapa: donde el café de autor se vive con arte, música y comunidad',
      rationale:'Compite con cafeterías de especialidad por calidad y con espacios culturales por experiencia, pero no es exactamente ninguna de las dos. La posición se sostiene en la combinación, que es difícil de copiar sin la curaduría.'}),
    Object.freeze({module:'Core Message',
      option:'Un café que se queda contigo',
      rationale:'Dice a la vez la calidad de la taza y la razón de volver: la experiencia que la acompaña. Es recordable y no promete nada que la marca no entregue.'})
  ]),
  hypothesis:'Hipótesis demo: si las Coffee Raves se sostienen una vez al mes, la visita entre semana crecerá porque quien viene al evento regresa a trabajar o a conversar. Sin validar.',
  userInput:'Aporte demo del Estratega de Marca: la escena cultural de Xalapa es fuerte y está dispersa; no existe un lugar que sea a la vez café de autor y punto de encuentro cultural estable.'
});

export const ACCESS_STATUS=Object.freeze({pending:'PENDING',approved:'APPROVED',suspended:'SUSPENDED'} as const);
export type AccessStatus=typeof ACCESS_STATUS[keyof typeof ACCESS_STATUS];
export const ACCESS_STATUSES:readonly AccessStatus[]=Object.freeze(Object.values(ACCESS_STATUS));
/** Claims taken from a validated ID token. Never populated from anything the browser sends. */
export interface VerifiedClaims {subject:string;email?:string;emailVerified?:boolean;displayName?:string|null;avatarUrl?:string|null}
export interface VerifiedProfile {email:string;normalizedEmail:string;displayName:string|null;avatarUrl:string|null}

export class PilotAccess {
  constructor(private db:Database,readonly issuer:string) {}
  async provision(subject:string,cohort:string,workspaceId?:string,account?:VerifiedProfile,accessStatus:AccessStatus=ACCESS_STATUS.approved) {
    if(!subject.trim()||subject.length>500||!['A','B'].includes(cohort))throw new AppError('INVALID','Invalid tester');
    if(!ACCESS_STATUSES.includes(accessStatus))throw new AppError('INVALID','Invalid access status');
    return this.db.transaction(async tx=>{
      if((await tx.select().from(t.pilotIdentities).where(and(eq(t.pilotIdentities.issuer,this.issuer),eq(t.pilotIdentities.subject,subject)))).length)throw new AppError('CONFLICT','Tester already provisioned');
      const userId=randomUUID(),wid=workspaceId??randomUUID(),now=new Date();
      if(workspaceId){if(!(await tx.select().from(t.pilotWorkspaces).where(and(eq(t.pilotWorkspaces.workspaceId,wid),eq(t.pilotWorkspaces.cohort,cohort))))[0])throw new AppError('INVALID','PILOT workspace and cohort required');}
      else {await tx.insert(t.workspaces).values({id:wid,name:'Workspace PILOT'});await tx.insert(t.pilotWorkspaces).values({workspaceId:wid,cohort,createdAt:now});}
      await tx.insert(t.users).values({id:userId});
      await tx.insert(t.memberships).values({workspaceId:wid,userId,role:'MEMBER',active:true,canCreateBrand:true});
      await tx.insert(t.pilotIdentities).values({userId,issuer:this.issuer,subject,workspaceId:wid});
      if(account)await tx.insert(t.userAccounts).values({userId,email:account.email,normalizedEmail:account.normalizedEmail,emailVerifiedAt:now,displayName:account.displayName??null,avatarUrl:account.avatarUrl??null,createdAt:now,lastLoginAt:now,accessStatus});
      await tx.insert(t.pilotEvents).values({id:randomUUID(),userId,workspaceId:wid,name:'account_created',cohort,intervention:'NONE',occurredAt:now});
      return {userId,workspaceId:wid};
    });
  }
  /**
   * Seeds the CoffeePolis sandbox into a PILOT workspace that has no brands yet. Each participant gets
   * their own editable copy: nothing is shared across workspaces. Idempotent, and never backfills a
   * workspace that already holds brands, so existing engineering fixtures stay untouched.
   */
  async ensureDemoBrand(token:string) {
    const who=await this.authorize(token) as {userId:string;workspaceId:string};
    const [pilot]=await this.db.select().from(t.pilotWorkspaces).where(eq(t.pilotWorkspaces.workspaceId,who.workspaceId));
    if(!pilot)return null;
    // Self-service participants only. An operator-provisioned identity has no account profile, so
    // engineering fixtures and manually provisioned testers are never seeded or back-filled.
    const [account]=await this.db.select().from(t.userAccounts).where(eq(t.userAccounts.userId,who.userId));
    if(!account)return null;
    const existing=await this.db.select().from(t.brands).where(eq(t.brands.workspaceId,who.workspaceId));
    if(existing.length)return null;
    const brand=await new Engine(this.db).createBrand(token,DEMO_BRAND.name,DEMO_BRAND.context);
    await this.db.insert(t.brandProfiles).values({workspaceId:who.workspaceId,brandId:brand.id,isDemo:true,
      geographicInfluence:DEMO_BRAND.geographicInfluence,primaryMarket:DEMO_BRAND.primaryMarket}).onConflictDoNothing();
    return brand;
  }
  /**
   * Fills the CoffeePolis sandbox with its demonstration strategy.
   *
   * UPGRADE RULE, deliberately conservative:
   *  - only ever touches a brand classified isDemo=true, never a real one;
   *  - runs only when the demo brand has NO approved decision version at all, so a participant who has
   *    already explored and decided inside it keeps their work untouched;
   *  - never resets, never deletes, never rewrites an existing version;
   *  - safe to call on every sign-in: once content exists the first check returns immediately, so
   *    repetition cannot duplicate decisions, events or context.
   * That makes it correct for both a fresh workspace and one seeded before this content existed.
   */
  async ensureDemoContent(token:string){
    const who=await this.authorize(token) as {userId:string;workspaceId:string};
    const demoIds=new Set((await this.db.select().from(t.brandProfiles)
      .where(and(eq(t.brandProfiles.workspaceId,who.workspaceId),eq(t.brandProfiles.isDemo,true)))).map(b=>b.brandId));
    if(!demoIds.size)return null;
    const [brand]=await this.db.select().from(t.brands)
      .where(and(eq(t.brands.workspaceId,who.workspaceId),inArray(t.brands.id,[...demoIds])));
    if(!brand)return null;
    // Any approved version means a participant (or a previous run) already worked here: leave it alone.
    const existing=await this.db.select().from(t.versions)
      .where(and(eq(t.versions.workspaceId,who.workspaceId),eq(t.versions.brandId,brand.id)));
    if(existing.length)return null;

    const engine=new Engine(this.db);
    const context=await engine.context(token,brand.id) as {questions:{id:string;module:string}[]};
    // A sandbox created before ADR-0021 lacks the new sections: they are skipped, never added here.
    let seeded=0;
    for(const step of DEMO_STRATEGY.decisions){
      const question=context.questions.find(q=>q.module===step.module);
      if(!question)continue;
      try{
        await engine.prepareQuestion(token,brand.id,question.id,null);
        await engine.commitDecision(token,{brandId:brand.id,questionId:question.id,selectedOption:step.option,
          rationale:step.rationale,expectedActiveVersion:null,actorUserId:who.userId,sourceRecommendationId:null,
          idempotencyKey:`demo:${brand.id}:${step.module}`});
        seeded++;
      }catch{/* a demo that cannot be fully seeded is still usable; never block the session */}
    }
    try{
      await engine.captureContext(token,brand.id,'user-input',{statement:DEMO_STRATEGY.userInput},`demo-input:${brand.id}`);
      await engine.captureContext(token,brand.id,'hypothesis',{statement:DEMO_STRATEGY.hypothesis},`demo-hypothesis:${brand.id}`);
    }catch{/* context is illustrative; its absence must not fail a sign-in */}
    return {brandId:brand.id,decisions:seeded};
  }
  /** Strategic geography for a brand the participant owns. Absent row means no declared market. */
  async setBrandGeography(token:string,brandId:string,influence:GeographicInfluence,primaryMarket?:string|null) {
    if(!GEOGRAPHIC_INFLUENCE.includes(influence))throw new AppError('INVALID','Invalid geographic influence');
    if(primaryMarket!=null&&(typeof primaryMarket!=='string'||primaryMarket.length>160))throw new AppError('INVALID','Invalid primary market');
    const who=await this.authorize(token) as {workspaceId:string};
    const [brand]=await this.db.select().from(t.brands).where(and(eq(t.brands.id,brandId),eq(t.brands.workspaceId,who.workspaceId)));
    if(!brand)throw new AppError('NOT_FOUND','Brand unavailable');
    await this.db.insert(t.brandProfiles).values({workspaceId:who.workspaceId,brandId,isDemo:false,geographicInfluence:influence,primaryMarket:primaryMarket??null})
      .onConflictDoUpdate({target:[t.brandProfiles.workspaceId,t.brandProfiles.brandId],set:{geographicInfluence:influence,primaryMarket:primaryMarket??null}});
    return {brandId,geographicInfluence:influence,primaryMarket:primaryMarket??null};
  }
  /** Participant intake, once per account. Email is never taken from here: it comes from the ID token. */
  async saveParticipantProfile(token:string,input:Record<string,unknown>) {
    const who=await this.authorize(token) as {userId:string};
    const text=(key:string,max:number,required:boolean)=>{
      const value=input[key];
      if(value==null||value===''){if(required)throw new AppError('INVALID',`${key} required`);return null;}
      if(typeof value!=='string'||value.trim().length===0||value.length>max)throw new AppError('INVALID',`Invalid ${key}`);
      return value.trim();
    };
    if(input.privacyAccepted!==true||input.termsAccepted!==true)throw new AppError('INVALID','Privacy and terms acceptance required');
    if(!PARTICIPANT_PROFILES.includes(String(input.primaryProfile) as ParticipantProfile))throw new AppError('INVALID','Invalid primaryProfile');
    const now=new Date();
    const row={userId:who.userId,firstName:text('firstName',80,true)!,lastName:text('lastName',80,true)!,
      country:text('country',80,true)!,region:text('region',80,true)!,city:text('city',80,true)!,
      primaryProfile:String(input.primaryProfile),companyOrProject:text('companyOrProject',160,false),
      sector:text('sector',120,false),pilotGoal:text('pilotGoal',1200,false),
      privacyAcceptedAt:now,termsAcceptedAt:now,createdAt:now,updatedAt:now};
    await this.db.insert(t.participantProfiles).values(row)
      .onConflictDoUpdate({target:t.participantProfiles.userId,set:{...row,createdAt:undefined,updatedAt:now}});
    return {complete:true};
  }
  /**
   * Whether the participant still owes intake. Only self-service accounts do: an operator-provisioned
   * identity has no account profile, so legacy testers and engineering fixtures are exempt and keep
   * working exactly as before. Never invents profile data for them.
   */
  async intakeRequired(token:string) {
    const who=await this.authorize(token) as {userId:string};
    const [account]=await this.db.select().from(t.userAccounts).where(eq(t.userAccounts.userId,who.userId));
    if(!account)return false;
    const [profile]=await this.db.select().from(t.participantProfiles).where(eq(t.participantProfiles.userId,who.userId));
    return !profile;
  }
  async participantProfile(token:string) {
    const who=await this.authorize(token) as {userId:string};
    const [row]=await this.db.select().from(t.participantProfiles).where(eq(t.participantProfiles.userId,who.userId));
    return row??null;
  }
  async assign(userId:string,brandId:string) {
    await this.db.transaction(async tx=>{
      const [who]=await tx.select().from(t.pilotIdentities).where(eq(t.pilotIdentities.userId,userId));
      if(!who?.active)throw new AppError('FORBIDDEN','Tester unavailable');
      const [brand]=await tx.select().from(t.brands).where(and(eq(t.brands.id,brandId),eq(t.brands.workspaceId,who.workspaceId),eq(t.brands.dataClass,'PILOT')));
      if(!brand)throw new AppError('NOT_FOUND','Brand unavailable');
      await tx.insert(t.assignments).values({userId,brandId,workspaceId:who.workspaceId}).onConflictDoNothing();
    });
  }
  /** Moves a self-service participant through the access lifecycle. Withdrawing access also drops live
   *  sessions, so suspension is immediate rather than effective at the next sign-in. */
  async setAccessStatus(userId:string,status:AccessStatus) {
    if(!ACCESS_STATUSES.includes(status))throw new AppError('INVALID','Invalid access status');
    return this.db.transaction(async tx=>{
      const [profile]=await tx.select().from(t.userAccounts).where(eq(t.userAccounts.userId,userId)).for('update');
      if(!profile)throw new AppError('NOT_FOUND','Participant profile unavailable');
      await tx.update(t.userAccounts).set({accessStatus:status}).where(eq(t.userAccounts.userId,userId));
      if(status!==ACCESS_STATUS.approved)await tx.delete(t.sessions).where(eq(t.sessions.userId,userId));
      return {userId,accessStatus:status};
    });
  }
  async disable(userId:string) {
    await this.db.transaction(async tx=>{
      const [who]=await tx.select().from(t.pilotIdentities).where(eq(t.pilotIdentities.userId,userId)).for('update');
      if(!who)throw new AppError('NOT_FOUND','Tester unavailable');
      await tx.update(t.pilotIdentities).set({active:false}).where(eq(t.pilotIdentities.userId,userId));
      await tx.update(t.memberships).set({active:false}).where(and(eq(t.memberships.userId,userId),eq(t.memberships.workspaceId,who.workspaceId)));
      await tx.delete(t.sessions).where(eq(t.sessions.userId,userId));
    });
  }
  async inspect(ref:{userId?:string;subject?:string}) {
    const [who]=await this.db.select().from(t.pilotIdentities).where(ref.userId?eq(t.pilotIdentities.userId,ref.userId):and(eq(t.pilotIdentities.issuer,this.issuer),eq(t.pilotIdentities.subject,String(ref.subject??''))));
    if(!who)throw new AppError('NOT_FOUND','Tester unavailable');
    const [member]=await this.db.select().from(t.memberships).where(and(eq(t.memberships.workspaceId,who.workspaceId),eq(t.memberships.userId,who.userId)));
    const [account]=await this.db.select().from(t.userAccounts).where(eq(t.userAccounts.userId,who.userId));
    const [workspace]=await this.db.select().from(t.pilotWorkspaces).where(eq(t.pilotWorkspaces.workspaceId,who.workspaceId));
    const brands=await this.db.select({id:t.brands.id,name:t.brands.name}).from(t.assignments).innerJoin(t.brands,and(eq(t.brands.id,t.assignments.brandId),eq(t.brands.workspaceId,t.assignments.workspaceId))).where(and(eq(t.assignments.userId,who.userId),eq(t.assignments.workspaceId,who.workspaceId)));
    const sessions=await this.db.select().from(t.sessions).where(and(eq(t.sessions.userId,who.userId),gt(t.sessions.expiresAt,new Date())));
    // Subject is shown for operator correlation only; session tokens are never exposed.
    return {userId:who.userId,issuer:who.issuer,subject:who.subject,workspaceId:who.workspaceId,cohort:workspace?.cohort??null,identityActive:who.active,accessStatus:account?.accessStatus??ACCESS_STATUS.approved,membershipActive:member?.active??false,role:member?.role??null,brands,activeSessions:sessions.length};
  }
  async revokeSessions(userId:string) {
    const [who]=await this.db.select().from(t.pilotIdentities).where(eq(t.pilotIdentities.userId,userId));
    if(!who)throw new AppError('NOT_FOUND','Tester unavailable');
    return {revoked:(await this.db.delete(t.sessions).where(eq(t.sessions.userId,userId)).returning()).length};
  }
  // Activation = first strategic Decision approved. Durations in seconds from the tester's first session.
  /**
   * D7/D14/D30 from stored timestamps: activated participants with a High-Value Strategic Event inside
   * the window, day ±1 as the canonical definition requires. Returns null — not false — while the window
   * has not fully elapsed for that participant, so "not yet observable" never reads as "did not return".
   */
  private static retentionWindows(events:{name:string;occurredAt:Date}[],activation:Date|undefined,hve:string[],now=new Date()):
    {retainedD7:boolean|null;retainedD14:boolean|null;retainedD30:boolean|null} {
    const inWindow=(day:number)=>{
      if(!activation)return null;
      const opensAt=activation.getTime()+(day-1)*86400000,closesAt=activation.getTime()+(day+1)*86400000;
      // The window must be fully in the past before an absence can mean anything.
      if(now.getTime()<closesAt)return null;
      return events.some(e=>hve.includes(e.name)&&e.occurredAt.getTime()>=opensAt&&e.occurredAt.getTime()<=closesAt);
    };
    return {retainedD7:inWindow(7),retainedD14:inWindow(14),retainedD30:inWindow(30)};
  }
  async metrics() {
    const rows=await this.db.select().from(t.pilotEvents).orderBy(asc(t.pilotEvents.occurredAt));
    // Demo brands are classified server-side, never inferred from a name. Every brand-scoped event that
    // belongs to a demo brand is removed before any participant metric is computed, so CoffeePolis can
    // never fabricate a brand count, an activation, a time-to-first-decision or a second-brand signal.
    const demo=new Set((await this.db.select().from(t.brandProfiles).where(eq(t.brandProfiles.isDemo,true))).map(b=>b.brandId));
    const isDemoEvent=(e:{brandId:string|null})=>Boolean(e.brandId&&demo.has(e.brandId));
    const users=new Map<string,typeof rows>();for(const r of rows)users.set(r.userId,[...(users.get(r.userId)??[]),r]);
    const demoByUser=new Map<string,typeof rows>();for(const r of rows)if(isDemoEvent(r))demoByUser.set(r.userId,[...(demoByUser.get(r.userId)??[]),r]);
    const first=(events:typeof rows,name:string)=>events.find(e=>e.name===name)?.occurredAt;
    const since=(a?:Date,b?:Date)=>a&&b?Math.round((b.getTime()-a.getTime())/1000):null;
    return [...users].map(([userId,all])=>{
      const events=all.filter(e=>!isDemoEvent(e));
      const demoEvents=demoByUser.get(userId)??[];
      // Canonical anchor: the brand. session_started is only a fallback for events that predate a brand.
      const brandStart=first(events,'brand_created'),start=brandStart??first(events,'session_started');
      const decisions=events.filter(e=>e.name==='decision_created');
      // Canonical High-Value Strategic Events (Master Context §45); activation is the first approved Decision.
      const activation=decisions[0]?.occurredAt,hve=['strategic_question_started','decision_created','change_impact_review_completed','dependency_triggered','experiment_created','signal_added','learning_created'];
      const secondHighValueEvent14d=Boolean(activation)&&events.some(e=>hve.includes(e.name)&&e.occurredAt>activation!&&e.occurredAt.getTime()-activation!.getTime()<=14*86400000);
      const retention=(rows:typeof events,at:Date|undefined)=>PilotAccess.retentionWindows(rows,at,hve);
      return {userId,cohort:events[0].cohort,sessions:events.filter(e=>e.name==='session_started').length,brands:new Set(events.filter(e=>e.name==='brand_created').map(e=>e.brandId)).size,
        recommendationsRequested:events.filter(e=>e.name==='recommendation_requested').length,recommendationsFailed:events.filter(e=>e.name==='analysis_failed').length,
        decisionsApproved:decisions.length,activated:decisions.length>0,reviewsCompleted:events.filter(e=>e.name==='change_impact_review_completed').length,
        secondHighValueEvent14d,timeToFirstInsightSeconds:since(start,first(events,'recommendation_generated')),timeToFirstDecisionSeconds:since(start,decisions[0]?.occurredAt),
        // Mapa estratégico: viewing the connected map and taking it away are different acts, so they are
        // counted separately. The export has its own event because it reuses the same read.
        mapaEstrategicoViewed:events.some(e=>e.name==='blueprint_viewed'),
        mapaEstrategicoExports:events.filter(e=>e.name==='blueprint_pdf_exported').length,
        // Evidence Engagement, canonical: exposed to a Recommendation, and opened Evidence.
        exposedToRecommendation:events.some(e=>e.name==='recommendation_generated'),
        openedEvidence:events.some(e=>e.name==='evidence_panel_opened'),
        // Evidence actually supplied or curated. Stronger than opening, reported alongside rather than
        // folded into the canonical rate, which is deliberately about opening.
        evidenceSupplied:events.filter(e=>e.name==='evidence_added').length,
        documentsUploaded:events.filter(e=>e.name==='source_document_uploaded').length,
        documentClaimsGenerated:events.filter(e=>e.name==='document_claims_generated').length,
        // Retention: derived from timestamps, never from a client-side "returned" flag. Null while the
        // window has not elapsed yet, so an unobserved participant is never counted as churned.
        ...retention(events,activation),
        // Demo exploration is reported separately so it stays visible without ever counting as real work.
        demoBrands:new Set(demoEvents.filter(e=>e.name==='brand_created').map(e=>e.brandId)).size,
        demoDecisions:demoEvents.filter(e=>e.name==='decision_created').length};
    });
  }
  // AI guardrails for PILOT: one acknowledgement per notice version (append-only event, no schema change)
  // and rolling 24 h request caps per tester and in total. A cap of 0 disables AI requests.
  async aiGate(token:string,policy:{noticeVersion:string|null;capPerTester:number;capTotal:number}):Promise<'OK'|'CONSENT_REQUIRED'|'CAP_REACHED'> {
    const who=await this.authorize(token),since=new Date(Date.now()-86400000);
    if(policy.noticeVersion){
      const [accepted]=await this.db.select({id:t.pilotEvents.id}).from(t.pilotEvents).where(and(eq(t.pilotEvents.userId,who.userId),eq(t.pilotEvents.name,'ai_notice_accepted:'+policy.noticeVersion))).limit(1);
      if(!accepted)return 'CONSENT_REQUIRED';
    }
    const requested=and(or(eq(t.pilotEvents.name,'recommendation_requested'),eq(t.pilotEvents.name,'brando_requested')),gt(t.pilotEvents.occurredAt,since));
    const [mine]=await this.db.select({n:count()}).from(t.pilotEvents).where(and(requested,eq(t.pilotEvents.userId,who.userId)));
    const [all]=await this.db.select({n:count()}).from(t.pilotEvents).where(requested);
    return mine.n>=policy.capPerTester||all.n>=policy.capTotal?'CAP_REACHED':'OK';
  }
  async acceptAiNotice(token:string,version:string) {
    const who=await this.authorize(token);
    if(!/^[a-f0-9]{12}$/.test(version))throw new AppError('INVALID','Invalid notice version');
    const [workspace]=await this.db.select().from(t.pilotWorkspaces).where(eq(t.pilotWorkspaces.workspaceId,who.workspaceId));
    const [session]=await this.db.select().from(t.pilotSessions).where(eq(t.pilotSessions.sessionId,who.sessionId));
    await this.db.insert(t.pilotEvents).values({id:randomUUID(),userId:who.userId,workspaceId:who.workspaceId,sessionId:who.sessionId,name:'ai_notice_accepted:'+version,cohort:workspace.cohort,intervention:session?.intervention??'NONE',occurredAt:new Date()});
    return {accepted:true};
  }
  // Aggregate Pilot evidence for the operator: counts, rates and durations only; no strategy text, no subjects.
  async report() {
    const people=await this.metrics(),feedback=await this.db.select().from(t.feedback);
    const stats=(values:(number|null)[])=>{const v=values.filter((x):x is number=>x!==null).sort((a,b)=>a-b);if(!v.length)return {n:0,medianSeconds:null,averageSeconds:null};
      const mid=Math.floor(v.length/2);return {n:v.length,medianSeconds:v.length%2?v[mid]:Math.round((v[mid-1]+v[mid])/2),averageSeconds:Math.round(v.reduce((a,b)=>a+b,0)/v.length)};};
    const distribution=(key:'usefulness'|'clarity'|'confidence')=>Object.fromEntries([1,2,3,4,5].map(n=>[n,feedback.filter(f=>f[key]===n).length]));
    const activated=people.filter(p=>p.activated).length,identities=await this.db.select().from(t.pilotIdentities);
    return {generatedAt:new Date().toISOString(),testers:identities.length,activeTesters:identities.filter(i=>i.active).length,testersWithSessions:people.filter(p=>p.sessions>0).length,
      activated,activationRate:identities.length?Math.round(activated/identities.length*1000)/1000:null,
      returningTesters:people.filter(p=>p.sessions>1).length,secondHighValueEvent14d:people.filter(p=>p.secondHighValueEvent14d).length,testersWithSecondBrand:people.filter(p=>p.brands>1).length,
      timeToFirstInsight:stats(people.map(p=>p.timeToFirstInsightSeconds)),timeToFirstDecision:stats(people.map(p=>p.timeToFirstDecisionSeconds)),
      ai:{requested:people.reduce((a,p)=>a+p.recommendationsRequested,0),failed:people.reduce((a,p)=>a+p.recommendationsFailed,0)},
      reviewsCompleted:people.reduce((a,p)=>a+p.reviewsCompleted,0),
      // Mapa estratégico: reached, and taken away. Separate acts, separately counted.
      mapaEstrategico:{
        viewed:people.filter(p=>p.mapaEstrategicoViewed).length,
        exportedParticipants:people.filter(p=>p.mapaEstrategicoExports>0).length,
        exports:people.reduce((a,p)=>a+p.mapaEstrategicoExports,0)
      },
      // Evidence Engagement, canonical: of those exposed to a Recommendation, how many opened Evidence.
      // The stronger acts of supplying and curating evidence are reported beside it, never folded in.
      evidence:{
        exposed:people.filter(p=>p.exposedToRecommendation).length,
        opened:people.filter(p=>p.openedEvidence).length,
        rate:(()=>{const exposed=people.filter(p=>p.exposedToRecommendation).length;
          return exposed?Math.round(people.filter(p=>p.exposedToRecommendation&&p.openedEvidence).length/exposed*1000)/1000:null;})(),
        participantsSupplying:people.filter(p=>p.evidenceSupplied>0).length,
        documentsUploaded:people.reduce((a,p)=>a+p.documentsUploaded,0),
        documentClaimsGenerated:people.reduce((a,p)=>a+p.documentClaimsGenerated,0)
      },
      // Retention: observed cases only. A null window is excluded from both numerator and denominator,
      // so an early Pilot reads as "not yet observable" instead of as churn.
      retention:Object.fromEntries((['retainedD7','retainedD14','retainedD30'] as const).map(key=>{
        const observed=people.filter(p=>p[key]!==null);
        return [key.replace('retained',''),{observed:observed.length,returned:observed.filter(p=>p[key]===true).length,
          rate:observed.length?Math.round(observed.filter(p=>p[key]===true).length/observed.length*1000)/1000:null}];
      })),
      feedback:{responses:feedback.filter(f=>f.kind==='FEEDBACK').length,issues:feedback.filter(f=>f.kind==='ISSUE').length,usefulness:distribution('usefulness'),clarity:distribution('clarity'),confidence:distribution('confidence')}};
  }
  /** Deterministic cohort from the canonical identity. The same identity always lands in the same arm,
   *  and an existing account is never reassigned because this is only consulted at first provisioning. */
  static cohortFor(issuer:string,subject:string) {
    return createHash('sha256').update(issuer+'\n'+subject).digest()[0]%2===0?'A':'B';
  }
  /** Recognises a verified external identity and, when auto-provisioning is on, creates the account on
   *  first sight. Identity stays (issuer, subject); the verified email is stored as profile metadata.
   *  Fail-closed by default: an unknown identity is denied unless autoProvision is explicitly enabled. */
  async recognise(claims:VerifiedClaims,autoProvision:boolean,defaultStatus:AccessStatus=ACCESS_STATUS.approved) {
    const subject=String(claims.subject??'').trim(),email=String(claims.email??'').trim();
    if(!subject)throw new AppError('FORBIDDEN','Identity not authorized');
    const verifiedEmail=Boolean(email)&&claims.emailVerified===true;
    const profile:VerifiedProfile={email,normalizedEmail:email.toLowerCase(),displayName:claims.displayName??null,avatarUrl:claims.avatarUrl??null};
    const seen=await this.identity(subject);
    // An identity provisioned by an operator keeps signing in on (issuer, subject) alone: a provider that
    // stops sending email claims must not lock an existing Estratega de Marca out. The profile is
    // refreshed only when the claims are actually verified.
    if(seen){if(verifiedEmail)await this.touchAccount(seen.userId,profile);return seen.userId;}
    if(!autoProvision)throw new AppError('FORBIDDEN','Identity not authorized');
    // Creating an account from nothing but an assertion demands a verified mailbox.
    if(!verifiedEmail)throw new AppError('FORBIDDEN','Verified email required');
    try {
      const {userId}=await this.provision(subject,PilotAccess.cohortFor(this.issuer,subject),undefined,profile,defaultStatus);
      return userId;
    } catch(error) {
      // A concurrent callback for the same identity loses the unique (issuer, subject) race. The winner's
      // account is the canonical one, so re-read instead of creating a second workspace.
      const again=await this.identity(subject);
      if(again){await this.touchAccount(again.userId,profile);return again.userId;}
      throw error;
    }
  }
  private async identity(subject:string) {
    const [who]=await this.db.select().from(t.pilotIdentities).where(and(eq(t.pilotIdentities.issuer,this.issuer),eq(t.pilotIdentities.subject,subject)));
    return who;
  }
  /** Refreshes the profile on every sign-in. If the mailbox already belongs to another account the email
   *  is left untouched rather than failing the login: identity is (issuer, subject), not the address. */
  private async touchAccount(userId:string,profile:VerifiedProfile) {
    const now=new Date();
    try {
      await this.db.insert(t.userAccounts)
        .values({userId,email:profile.email,normalizedEmail:profile.normalizedEmail,emailVerifiedAt:now,displayName:profile.displayName,avatarUrl:profile.avatarUrl,createdAt:now,lastLoginAt:now})
        .onConflictDoUpdate({target:t.userAccounts.userId,set:{email:profile.email,normalizedEmail:profile.normalizedEmail,emailVerifiedAt:now,displayName:profile.displayName,avatarUrl:profile.avatarUrl,lastLoginAt:now}});   // accessStatus deliberately untouched
    } catch {
      await this.db.update(t.userAccounts).set({lastLoginAt:now}).where(eq(t.userAccounts.userId,userId));
    }
  }
  async issueSession(subject:string) {
    return this.db.transaction(async tx=>{
      const [who]=await tx.select().from(t.pilotIdentities).where(and(eq(t.pilotIdentities.issuer,this.issuer),eq(t.pilotIdentities.subject,subject))).for('share');
      if(!who?.active)throw new AppError('FORBIDDEN','Tester not authorized');
      const [profile]=await tx.select().from(t.userAccounts).where(eq(t.userAccounts.userId,who.userId));
      if((profile?.accessStatus??ACCESS_STATUS.approved)!==ACCESS_STATUS.approved)throw new AppError('FORBIDDEN','Participant access not approved');
      const [member]=await tx.select().from(t.memberships).where(and(eq(t.memberships.workspaceId,who.workspaceId),eq(t.memberships.userId,who.userId))).for('share');
      if(!member?.active||!['MEMBER','ADMIN'].includes(member.role))throw new AppError('FORBIDDEN','Membership unavailable');
      const token=randomBytes(32).toString('base64url'),sessionId=randomUUID(),now=new Date(),expiresAt=new Date(now.getTime()+8*3600000);
      await tx.insert(t.sessions).values({tokenHash:hash(token),userId:who.userId,workspaceId:who.workspaceId,expiresAt});
      await tx.insert(t.pilotSessions).values({sessionId,tokenHash:hash(token),userId:who.userId,intervention:'PRODUCT_ONLY',startedAt:now});
      const [workspace]=await tx.select().from(t.pilotWorkspaces).where(eq(t.pilotWorkspaces.workspaceId,who.workspaceId));
      await tx.insert(t.pilotEvents).values({id:randomUUID(),userId:who.userId,workspaceId:who.workspaceId,sessionId,name:'session_started',cohort:workspace.cohort,intervention:'PRODUCT_ONLY',occurredAt:now});
      return {token,expiresAt};
    });
  }
  async authorize(token:string) {
    const who=await new Engine(this.db).me(token);
    const [identity]=await this.db.select().from(t.pilotIdentities).where(and(eq(t.pilotIdentities.userId,who.userId),eq(t.pilotIdentities.issuer,this.issuer),eq(t.pilotIdentities.active,true)));
    const [session]=await this.db.select().from(t.pilotSessions).where(eq(t.pilotSessions.tokenHash,hash(token)));
    if(!identity||identity.workspaceId!==who.workspaceId||!session)throw new AppError('FORBIDDEN','PILOT session required');
    const [profile]=await this.db.select().from(t.userAccounts).where(eq(t.userAccounts.userId,who.userId));
    if((profile?.accessStatus??ACCESS_STATUS.approved)!==ACCESS_STATUS.approved)throw new AppError('FORBIDDEN','Participant access not approved');
    return {...who,sessionId:session.sessionId};
  }
  async logout(token:string){await this.db.delete(t.sessions).where(eq(t.sessions.tokenHash,hash(token)));}
  async classifySession(sessionId:string,intervention:string){
    if(!['PRODUCT_ONLY','ASSISTED','CONCIERGE'].includes(intervention))throw new AppError('INVALID','Invalid intervention');
    const changed=await this.db.update(t.pilotSessions).set({intervention}).where(eq(t.pilotSessions.sessionId,sessionId)).returning();
    if(!changed.length)throw new AppError('NOT_FOUND','Session unavailable');
  }
  async saveFeedback(token:string,input:Record<string,unknown>) {
    const who=await this.authorize(token),brandId=String(input.brandId??'');
    await new Engine(this.db).context(token,brandId);
    if(!['usefulness','clarity','confidence'].every(k=>Number.isInteger(input[k])&&Number(input[k])>=1&&Number(input[k])<=5)||typeof input.comment!=='string'||input.comment.length>2000||!['FEEDBACK','ISSUE'].includes(String(input.kind)))throw new AppError('INVALID','Invalid feedback');
    const id=randomUUID();await this.db.insert(t.feedback).values({id,userId:who.userId,workspaceId:who.workspaceId,brandId,sessionId:who.sessionId,usefulness:Number(input.usefulness),clarity:Number(input.clarity),confidence:Number(input.confidence),comment:input.comment,kind:String(input.kind),createdAt:new Date()});return {id};
  }
}
